# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'CustomScanProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomScanProject

  target 'CustomScanProjectTests' do
    inherit! :search_paths
    # Pods for testing
      pod 'Masonry'
  end

  target 'CustomScanProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
